services:
  homey:
    image: ghcr.io/parthshahp/homey:latest
    container_name: homey
    restart: unless-stopped
    ports:
      - 30010:3000
    volumes:
      - ./config:/app/config.json
networks: {}
